POST http://localhost:3000/sms/user/signup
Content-Type: application/json

{
  "email": "nimaebrahimi@gmail.com",
  "user_name": "Pluto",
  "password": "nima1234"
}

###
POST http://localhost:3000/sms/user/signup
Content-Type: application/json

{
  "email": "plutoGay@gmail.com",
  "user_name": "PluPlu",
  "password": "nima1234"
}

###
GET http://localhost:3000/sms/user/login
Content-Type: application/json

{
  "email": "nimaebrahimi@gmail.com",
  "password": "nima1234"
}

###
GET http://localhost:3000/sms/user/login
Content-Type: application/json

{
  "email": "nimaebrahimi8282@gmail.com",
  "password": "nima1234"
}

###
GET http://localhost:3000/sms/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJleHAiOjE2ODkyNTg5MjMsIm5hbWUiOiJQbHV0byIsInN1YiI6MX0.13Yaz8qR4f7Fzz2-XCWAmGbanQmasaCwN6naBtBLeSY

###
GET http://localhost:3000/sms/user/buy

###
PUT http://localhost:3000/sms/user/buy/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsImV4cCI6MTY4OTA4MTc3MSwibmFtZSI6IlBsdXRvIiwic3ViIjoxfQ.XEK-FNffxKO68LKNUlNGbnn1asMqjU-xFfK94qe6G5w

###
PUT http://localhost:3000/sms/user/main/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsImV4cCI6MTY4OTA4MTc3MSwibmFtZSI6IlBsdXRvIiwic3ViIjoxfQ.XEK-FNffxKO68LKNUlNGbnn1asMqjU-xFfK94qe6G5w

###
PUT http://localhost:3000/sms/user/rent/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsImV4cCI6MTY4OTA4MTc3MSwibmFtZSI6IlBsdXRvIiwic3ViIjoxfQ.XEK-FNffxKO68LKNUlNGbnn1asMqjU-xFfK94qe6G5w

###
DELETE http://localhost:3000/sms/user/dropRent/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTY4ODQ4NDE4NCwibmFtZSI6IlBsdXRvIiwic3ViIjoxfQ.Jj1EnRMh0Bt72qurB4EEJVgZ8fLuuQW9FIWR6lhLiWA

###
GET http://localhost:3000/sms/payment/pay/10000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJleHAiOjE2ODkwMDI1ODUsIm5hbWUiOiJQbHV0byIsInN1YiI6MX0.NMk6Qao3YtV78z9LZGTEmdzpJmceZMGJIsbWnXDjoc0


###
POST http://localhost:3000/sms/user/contact/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsImV4cCI6MTY4OTA4MTc3MSwibmFtZSI6IlBsdXRvIiwic3ViIjoxfQ.XEK-FNffxKO68LKNUlNGbnn1asMqjU-xFfK94qe6G5w

{
  "name": "nigger",
  "phone": "+6454214845"
}

###
DELETE http://localhost:3000/sms/user/contacts/delete/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJleHAiOjE2ODkwMDQzNzAsIm5hbWUiOiJQbHV0byIsInN1YiI6MX0.UsMnkW9jrtOG_SrTnuyFqkydoABeEd4kWktoe8iasdc

###
POST http://localhost:3000/sms/user/template/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsImV4cCI6MTY4OTA4MTc3MSwibmFtZSI6IlBsdXRvIiwic3ViIjoxfQ.XEK-FNffxKO68LKNUlNGbnn1asMqjU-xFfK94qe6G5w

{
  "expression": "Hi im {{user_name}} and today is {{date}}"
}

###
DELETE http://localhost:3000/sms/user/template/delete/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJleHAiOjE2ODkwMDQzNzAsIm5hbWUiOiJQbHV0byIsInN1YiI6MX0.UsMnkW9jrtOG_SrTnuyFqkydoABeEd4kWktoe8iasdc




