POST http://localhost:3000/sms/user/signup
Content-Type: application/json

{
  "email": "nimaebrahimi@gmail.com",
  "user_name": "Pluto",
  "password": "nima1234"
}

###
POST http://localhost:3000/sms/user/signup
Content-Type: application/json

{
  "email": "pluto@gmail.com",
  "user_name": "nima",
  "password": "nima1234"
}

###
GET http://localhost:3000/sms/user/login
Content-Type: application/json

{
  "email": "nimaebrahimi@gmail.com",
  "password": "nima1234"
}

###
GET http://localhost:3000/sms/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTY4ODE0OTY2NiwibmFtZSI6IlBsdXRvIiwic3ViIjoxfQ.Wdbb9ioMUZvsornWjKZJPn3GpGgIrUOAuTnACcOr7hM
###
GET http://localhost:3000/sms/user/buy

###
GET http://localhost:3000/sms/payment/pay/1000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTY4ODEwODU2MSwibmFtZSI6Im5pbWEiLCJzdWIiOjF9.hPGr3tQlw3wPDkUNGZH9G6_YP_rrZONaC_cO0Xpc8o4


###
POST https://sandbox.zarinpal.com/pg/v4/payment/request.json
accept: application/json
Content-Type: application/json

{
  "merchant_id": "7b24c23a-ebb5-11e8-8df1-005056a205be",
  "amount": 10000,
  "callback_url": "http://yoursite.com/verify",
  "description": "افزایش اعتبار کاربر شماره ۱۱۳۴۶۲۹",
  "metadata": {
    "mobile": "09121234567",
    "email": "info.test@gmail.com"
  }
}

###

POST http://localhost:3000/sms/user/contacts/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTY4ODExNjk1OCwibmFtZSI6IlBsdXRvIiwic3ViIjoxfQ.qic1ci-0-XiOFEvc8XhjDinU4EAtYTOQO_d6sI0FLIM


{
  "name": "Nima",
  "phone": "+6451654845"
}

