POST http://localhost:3000/api/user/AddPassenger
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc0OTU0MjUsIm5hbWUiOiJQbHV0byIsInN1YiI6MX0.SPTK8Bnrz_SQNQqe0BrTdKPDKdeGbwXqiXHq43gcydw

{
  "first_name": "Navid",
  "last_name": "Ebrahimi",
  "gender": "Male",
  "date_of_birth": "000-0",
  "nationality": "Iran",
  "passport_number": "123456"
}

###
POST http://localhost:3000/api/user/AddPassenger
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc0OTU0MjUsIm5hbWUiOiJQbHV0byIsInN1YiI6MX0.SPTK8Bnrz_SQNQqe0BrTdKPDKdeGbwXqiXHq43gcydw

{
  "first_name": "Behzad",
  "last_name": "Ebram",
  "gender": "Female",
  "date_of_birth": "000-1",
  "nationality": "Iranian",
  "passport_number": "1234567"
}

###
POST http://localhost:3000/api/user/AddPassenger/Eqbalina
Content-Type: application/json

{
  "first_name": "Nima",
  "last_name": "Ebi",
  "gender": "Male",
  "date_of_birth": "000-0",
  "nationality": "Iran",
  "passport_number": "123456"
}

###
GET http://localhost:3000/api/user/passengers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc0OTU0MjUsIm5hbWUiOiJQbHV0byIsInN1YiI6MX0.SPTK8Bnrz_SQNQqe0BrTdKPDKdeGbwXqiXHq43gcydw

###
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc0OTU0MjUsIm5hbWUiOiJQbHV0byIsInN1YiI6MX0.SPTK8Bnrz_SQNQqe0BrTdKPDKdeGbwXqiXHq43gcydw